package com.github.mahui53541.kedacom.controller;

import com.github.mahui53541.kedacom.dao.UserDao;
import com.github.mahui53541.kedacom.domain.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;
import java.util.Map;


/**
 * @description:
 * @author: MaHui
 * @created: 2017/12/25 15:58
 * @version:1.0.0
 */
@Controller
@RequestMapping(path="/demo")
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDao userRepository;

    @GetMapping("/")
    public String welcome(Map<String, Object> model) {
        model.put("time", new Date());
        model.put("message", "sss");
        return "welcome";
    }
}
